# Generated by Django 3.0.2 on 2020-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('head0', models.CharField(default='', max_length=300)),
                ('chead', models.TextField(default='', max_length=3000)),
                ('head1', models.CharField(default='', max_length=300)),
                ('chead1', models.TextField(default='', max_length=300)),
                ('head2', models.CharField(default='', max_length=300)),
                ('chead2', models.TextField(default='', max_length=3000)),
            ],
        ),
    ]
