# Generated by Django 3.0.2 on 2020-04-06 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default='')),
                ('desc', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.TextField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=300)),
                ('state', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=300)),
                ('zip_code', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('desc', models.TextField(default='', max_length=3000)),
                ('value', models.IntegerField(default='')),
                ('category', models.TextField(default='', max_length=300)),
                ('subcategory', models.TextField(default='', max_length=300)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 6, 18, 25, 43, 584926), verbose_name='DATE')),
            ],
        ),
        migrations.CreateModel(
            name='Updateorder',
            fields=[
                ('update_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.TextField(default='', max_length=3000)),
                ('update_time', models.DateField(default=datetime.datetime(2020, 4, 6, 18, 25, 43, 585927), verbose_name='DATE')),
            ],
        ),
    ]
