# Generated by Django 3.0.2 on 2020-04-09 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellohello', '0002_auto_20200406_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 16, 19, 29, 537214), verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='updateorder',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 16, 19, 29, 540256), verbose_name='DATE'),
        ),
    ]
