# Generated by Django 3.0.2 on 2020-04-09 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellohello', '0003_auto_20200409_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 16, 28, 18, 610730), verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='updateorder',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 16, 28, 18, 611731), verbose_name='DATE'),
        ),
    ]
